name: My First Workflow
on:
  push: 
  
jobs:
  echo_the_date:
    runs-on: Windows-latest

    steps:
    - name: echo the date
      run: echo "The current time and date is $(date)" # Linux command 

    #- name: Stimulate a fail
    #  run: exit 1
    - name: echo the current branch
      run: echo ${{ github.ref_name }}


  test_and_deploy:
    runs-on: Windows-latest
    env:
      OPENWEATHERMAP_API: ${{ secrets.openweathermap_api }}
    steps:

    - name: Setup maven
      uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.2

    - name: Checkout the source
      uses: actions/checkout@v3  

    - name: Run test
      run: mvn clean test

