name: My First Workflow
on:
  push: 
    branches:
    - "deploy"

jobs:
  echo_the_date:
    runs-on: Windows-latest

    steps:
    - name: echo the date
      run: echo "The current time and date is $(date)" # Linux command 

    #- name: Stimulate a fail
    #  run: exit 1
    - name: Greeting to the world
      run: echo "Hell World"

    - name: echo the current branch
      run: echo ${{ github.ref_name }}

